version: '3'
services:
  discord-bot:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./.:/usr/src/app
    environment:
      - NODE_ENV=production
    command: >
      bash -c "npm install && npm start"